@baseUrl =  http://localhost:3000/api/auth


# @name Register
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "quocan2",
    "password": "123456",
    "confirmPassword": "123456"
}

###
# @name Login 
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "quocan",
    "password": "123456"
}

###

GET {{baseUrl}}/logout
