@baseUrl =  http://localhost:3000/api/categories

# User API

# @name Getall
GET {{baseUrl}} 

###

# @name GetbyId
GET {{baseUrl}}/64688848cdc1107fa4461943

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name": "Đồ văn phòng"
}

###

# @name Update
PUT {{baseUrl}}/update/64688cd6690f785ca3a1f2d6
Content-Type: application/json

{
   "name": "Đồ văn phòng"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64688848cdc1107fa4461943

###