@baseUrl =  http://localhost:3000/api/products

# Product API

# @name Getall
GET {{baseUrl}} 

###

# @name GetbyId
GET {{baseUrl}}/64688848cdc1107fa4461943

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name":"Ghế Gấp Văn Phòng Và Gia Đình Đa Năng, Ghế Văn Phòng Xếp Gọn - Hàng Chính Hãng",
    "urlImage":"24.webp",
    "price": 499000,
    "priceOld": 870000,
    "categoryId":"64688cd6690f785ca3a1f2d6",
    "userId":"64699e87b100f22f73e06d89"
}

###

# @name Update
PUT {{baseUrl}}/update/6469aabe96151524f40db0f9
Content-Type: application/json

{
    "name": "Máy giặt Samsung Inverter 8 kg WW80T3020WW - Chỉ giao HCM",
    "urlImage":"5.webp",
    "price": 4990000,
    "priceOld": 8000000,
    "categoryId":"64688c49690f785ca3a1f2ce",
    "userId":"64699e87b100f22f73e06d89"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/6469aa281918ced8f0f1feec

###