@baseUrl =  http://localhost:3000/api/users

# User API

# @name Getall
GET {{baseUrl}} 

###

# @name GetbyId
GET {{baseUrl}}/64699e87b100f22f73e06d89

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "username": "quocan",
    "phone": "0123456789",
    "password": "123456"
}

###

# @name Update
PUT {{baseUrl}}/update/64699e87b100f22f73e06d89
Content-Type: application/json

{
    "username": "quocan",
    "phone": "0123456789",
    "password": "123456"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64688d78690f785ca3a1f2d8

###