@baseUrl =  http://localhost:3000/api/videos

# User API

# @name Getall
GET {{baseUrl}} 

###

# @name GetbyId
GET {{baseUrl}}/id

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

# {
# "title":"SPA/MPA là gì",
# "description": "SPA/MPA là gì",
# "thumbnailUrl": "http://localhost:3000/images/videos/hq720.webp",
# "videoUrl"
# "viewCount"
# "likeCount"
# "dislikeCount"
# "shareCount"
# "videoLength"
# "status"
# "userId"
# "categoryId"
# "createdAt"
# "updatedAt"
# }

###

# @name Update
PUT {{baseUrl}}/update/645f2275d06e2c2249ebfd19
Content-Type: application/json

{
   "title": "Danh sách kết hợp"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/645f222ab6765148f6374ed9

###